Repository renanripee/Projeto_Adopt.me, pull requests merged in 2023-11, with the labels that each got.

#54 Adicionando Diagrama ER
  Documentação/Diagramas/Diagrama_Entidade_Relacionamento.mwb
  Documentação/Diagramas/Diagrama_Entidade_Relacionamento.mwb.bak
Labels: documentation

#56 34 implementação da funcionalidade cadastrar tutor no sistema
  .vscode/settings.json
  Documentação/Diagramas/Diagrama_Entidade_Relacionamento.mwb
  Documentação/Diagramas/Diagrama_Entidade_Relacionamento.mwb.bak
  api/.gitignore
  api/.mvn/wrapper/maven-wrapper.jar
  api/.mvn/wrapper/maven-wrapper.properties
  api/README.md
  api/mvnw
  api/mvnw.cmd
  api/pom.xml
  api/src/main/java/adopt/me/api/ApiApplication.java
  api/src/main/java/adopt/me/api/TutorController.java
  api/src/main/java/adopt/me/api/controller/endereco/DadosEndereco.java
  api/src/main/java/adopt/me/api/controller/endereco/Endereco.java
  api/src/main/java/adopt/me/api/controller/tutor/DadosCadastroTutor.java
  api/src/main/java/adopt/me/api/controller/tutor/Tutor.java
  api/src/main/java/adopt/me/api/controller/tutor/TutorRepository.java
  api/src/main/resources/application.yml
  api/src/main/resources/db/migration/V1__create-table-tutores.sql
  api/src/test/java/adopt/me/api/ApiApplicationTests.java
Labels: back-end

#57 Adicionando funcionalidade de Remoção
  api/src/main/java/adopt/me/api/TutorController.java
Labels: back-end

#58 Adicionando funcionalidade de Cadastro de Animais
  api/src/main/java/adopt/me/api/AnimalController.java
  api/src/main/java/adopt/me/api/controller/animal/Animal.java
  api/src/main/java/adopt/me/api/controller/animal/AnimalRepository.java
  api/src/main/java/adopt/me/api/controller/animal/DadosCadastroAnimal.java
  api/src/main/java/adopt/me/api/service/UploadImagemService.java
  api/src/main/resources/application.yml
  api/src/main/resources/db/migration/V2__create-table-animais.sql
  api/src/main/resources/static/imagens/1699745606261_EditarAdocao.png
Labels: back-end

#59 29 Listagem de Animais
  api/src/main/java/adopt/me/api/AnimalController.java
  api/src/main/java/adopt/me/api/controller/animal/DadosCadastroAnimal.java
Labels: back-end

#60 31 Edição Animal
  api/src/main/java/adopt/me/api/AnimalController.java
  api/src/main/java/adopt/me/api/controller/animal/Animal.java
  api/src/main/java/adopt/me/api/controller/animal/DadosEdicaoAnimal.java
Labels: back-end

#61 27 Remoção Animais
  api/src/main/java/adopt/me/api/AnimalController.java
  api/src/main/java/adopt/me/api/service/UploadImagemService.java
  api/src/main/resources/static/imagens/1699745606261_EditarAdocao.png
Labels: back-end

#63 42 Cadastrar Adoção
  api/src/main/java/adopt/me/api/controller/AdocaoController.java
  api/src/main/java/adopt/me/api/domain/adocao/Adocao.java
  api/src/main/java/adopt/me/api/domain/adocao/AdocaoDeAnimais.java
  api/src/main/java/adopt/me/api/domain/adocao/AdocaoRepository.java
  api/src/main/java/adopt/me/api/domain/adocao/DadosCadastroAdocao.java
  api/src/main/java/adopt/me/api/domain/animal/Animal.java
  api/src/main/java/adopt/me/api/domain/tutor/Tutor.java
  api/src/main/resources/db/migration/V4__create-table-adocoes.sql
  api/src/main/resources/static/imagens/1700008485296_EditarAdocao.png
  api/src/main/resources/static/imagens/1700011213777_ConfirmarExclus_o.png
  api/src/main/resources/static/imagens/1700011223519_ConfirmarExclus_o.png
  api/src/main/resources/static/imagens/1700011265253_ConfirmarExclus_o.png
  api/src/main/resources/static/imagens/1700011411746_Principal.png
  api/src/main/resources/static/imagens/1700011431364_Login.png
Labels: back-end

#68 44 Remoção Adoções
  api/src/main/java/adopt/me/api/controller/AdocaoController.java
  api/src/main/java/adopt/me/api/domain/adocao/AdocaoDeAnimais.java
  api/src/main/resources/static/imagens/1700091673383_ExibirAnimais.png
  api/src/main/resources/static/imagens/1700091715112_EditarTutor.png
Labels: back-end

#71 Adicionando a tela Cadastrar Tutor
  web/src/Routes.tsx
  web/src/pages/Tutores/TutoresNew/TutoresNew.tsx
Labels: front-end

#75 Back
  .gitignore
  .vs/Projeto_Adopt.me/v16/.suo
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  .vscode/settings.json
  api/.gitignore
  api/.mvn/wrapper/maven-wrapper.jar
  api/.mvn/wrapper/maven-wrapper.properties
  api/README.md
  api/mvnw
  api/mvnw.cmd
  api/pom.xml
  api/src/main/java/adopt/me/api/ApiApplication.java
  api/src/main/java/adopt/me/api/controller/AdocaoController.java
  api/src/main/java/adopt/me/api/controller/AnimalController.java
  api/src/main/java/adopt/me/api/controller/AutenticacaoController.java
  api/src/main/java/adopt/me/api/controller/TutorController.java
  api/src/main/java/adopt/me/api/domain/adocao/Adocao.java
  api/src/main/java/adopt/me/api/domain/adocao/AdocaoDeAnimais.java
  api/src/main/java/adopt/me/api/domain/adocao/AdocaoRepository.java
  api/src/main/java/adopt/me/api/domain/adocao/DadosCadastroAdocao.java
  api/src/main/java/adopt/me/api/domain/adocao/DadosDetalhamentoAdocao.java
  api/src/main/java/adopt/me/api/domain/adocao/DadosEdicaoAdocao.java
  api/src/main/java/adopt/me/api/domain/animal/Animal.java
  api/src/main/java/adopt/me/api/domain/animal/AnimalRepository.java
  api/src/main/java/adopt/me/api/domain/animal/DadosCadastroAnimal.java
  api/src/main/java/adopt/me/api/domain/animal/DadosDetalhamentoAnimal.java
  api/src/main/java/adopt/me/api/domain/animal/DadosEdicaoAnimal.java
  api/src/main/java/adopt/me/api/domain/endereco/DadosEndereco.java
  api/src/main/java/adopt/me/api/domain/endereco/Endereco.java
  api/src/main/java/adopt/me/api/domain/tutor/DadosCadastroTutor.java
  api/src/main/java/adopt/me/api/domain/tutor/DadosDetalhamentoTutor.java
  api/src/main/java/adopt/me/api/domain/tutor/DadosEdicaoTutor.java
  api/src/main/java/adopt/me/api/domain/tutor/Tutor.java
  api/src/main/java/adopt/me/api/domain/tutor/TutorRepository.java
  api/src/main/java/adopt/me/api/domain/usuario/AutenticationService.java
  api/src/main/java/adopt/me/api/domain/usuario/DadosAutenticacao.java
  api/src/main/java/adopt/me/api/domain/usuario/Usuario.java
  api/src/main/java/adopt/me/api/domain/usuario/UsuarioRepository.java
  api/src/main/java/adopt/me/api/domain/usuario/UsuarioService.java
  api/src/main/java/adopt/me/api/infra/exception/TratadorDeErros.java
  api/src/main/java/adopt/me/api/infra/file/AnimalAndFileService.java
  api/src/main/java/adopt/me/api/infra/security/DadosTokenJWT.java
  api/src/main/java/adopt/me/api/infra/security/SecurityConfigurations.java
  api/src/main/java/adopt/me/api/infra/security/SecurityFilter.java
  api/src/main/java/adopt/me/api/infra/security/TokenService.java
  api/src/main/resources/application.yml
  api/src/main/resources/db/migration/V1__create-table-tutores.sql
  api/src/main/resources/db/migration/V2__create-table-animais.sql
  api/src/main/resources/db/migration/V3__create-table-usuarios.sql
  api/src/main/resources/db/migration/V4__create-table-adocoes.sql
Labels: back-end

#77 26 criação da tela cadastrar animal
  web/src/Routes.tsx
  web/src/assets/adicionar-imagem.png
  web/src/assets/hover.png
  web/src/components/AnimalForm/AnimalForm.css
  web/src/components/AnimalForm/AnimalForm.tsx
  web/src/components/Cards/Card/Card.tsx
  web/src/components/Cards/CardList/CardListAdocao.tsx
  web/src/components/Cards/CardList/CardListAnimal.tsx
  web/src/components/Header/Header.css
  web/src/components/Login/LoginButton/LoginButton.css
  web/src/components/TutorForm/TutorForm.css
  web/src/components/TutorForm/TutorForm.tsx
  web/src/interfaces/animal.ts
  web/src/views/Animal/Animais.css
  web/src/views/Animal/CadastrarAnimal.tsx
  web/src/views/Animal/ExibirAnimais.tsx
  web/src/views/Animal/animais.json
  web/src/views/Home/Principal.tsx
Labels: front-end

#78 Adicionando a tela de Edição de Animal
  web/src/Routes.tsx
  web/src/components/AnimalForm/AnimalForm.css
  web/src/components/AnimalForm/AnimalForm.tsx
  web/src/components/Cards/Card/Card.tsx
  web/src/components/Cards/CardList/CardListAdocao.tsx
  web/src/components/Cards/CardList/CardListAnimal.tsx
  web/src/interfaces/animal.ts
  web/src/views/Animal/EditarAnimal.tsx
Labels: front-end

#79 Adicionando a tela de Remover Animal
  web/src/components/AnimalForm/AnimalForm.tsx
Labels: front-end

#81 Adicionando Tela de Editar Adocao
  web/src/Routes.tsx
  web/src/components/AdocaoForm/AdocaoForm.css
  web/src/components/AdocaoForm/AdocaoForm.tsx
  web/src/components/AnimalForm/AnimalForm.tsx
  web/src/components/Cards/Card/Card.css
  web/src/components/Imagem/Imagem.tsx
  web/src/components/Table/itens.json
  web/src/components/TutorForm/TutorForm.css
  web/src/components/TutorForm/TutorForm.tsx
  web/src/interfaces/Adocao.ts
  web/src/interfaces/tutor.ts
  web/src/views/Animal/animais.json
  web/src/views/adocao/EditarAdocao.tsx
Labels: front-end
